### PR TITLE
Feature/filter styling

### PR DESCRIPTION
**Pull request by ewilloughby**
@dellurea Quick PR for the filter styling changes.

### CODE REVIEW

**Comment by dellurea** [comment]
@ewilloughby checking this out in beta... something doesn't look right (chrome)

**Comment by dellurea** [comment]
@ewilloughby I don't think the filters are showing up bolded in my browser

**Comment by ewilloughby** [comment]
@dellurea Hold shift key and refresh to reload javascript and css files - they are showing up for me.

**Comment by dellurea** [comment]
@ewilloughby I had tried that... still not seeing it. But it looks ok in firefox... maybe i'm just going cross eyed

**Pull request merged**
